### ISSUE TITLE
Add an CC license for non code parts of the page

### ISSUE THREAD

**Issue by tfoerst3r** [btschwertfeger/Growth-Model-Website#2]
Code and Text Licenses should have different license types.

My suggestion:
- code: MIT
- text/images CC-BY-4.0

**Comment by btschwertfeger** [comment]
What would you suggest as to how this should be applied? Having two license files is confusing and separating the text and code is also not possible. Creating a `text` or static directory containing only text files which get included in the code/html files makes it somewhat dirty.

We could add the license statement for the text and images in the readme when working on #1.

**Comment by btschwertfeger** [comment]
We could also make everything CC-By-4.0 since the code must not be licensed by MIT.
